/*
 * Copyright (c) 2021 SAP SE or an SAP affiliate company and XSK contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, v2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and XSK contributors
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.sap.ndb.bimodeldimension;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sap.ndb.bimodeldimension package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sap.ndb.bimodeldimension
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Dimension }
   */
  public Dimension createDimension() {
    return new Dimension();
  }

  /**
   * Create an instance of {@link LocalDimension }
   */
  public LocalDimension createLocalDimension() {
    return new LocalDimension();
  }

  /**
   * Create an instance of {@link DerivedDimension }
   */
  public DerivedDimension createDerivedDimension() {
    return new DerivedDimension();
  }

  /**
   * Create an instance of {@link Hierarchies }
   */
  public Hierarchies createHierarchies() {
    return new Hierarchies();
  }

  /**
   * Create an instance of {@link ParentChildHierarchy }
   */
  public ParentChildHierarchy createParentChildHierarchy() {
    return new ParentChildHierarchy();
  }

  /**
   * Create an instance of {@link SiblingOrder }
   */
  public SiblingOrder createSiblingOrder() {
    return new SiblingOrder();
  }

  /**
   * Create an instance of {@link AttributeParentPair }
   */
  public AttributeParentPair createAttributeParentPair() {
    return new AttributeParentPair();
  }

  /**
   * Create an instance of {@link HierarchyTimeProperties }
   */
  public HierarchyTimeProperties createHierarchyTimeProperties() {
    return new HierarchyTimeProperties();
  }

  /**
   * Create an instance of {@link EdgeAttribute }
   */
  public EdgeAttribute createEdgeAttribute() {
    return new EdgeAttribute();
  }

  /**
   * Create an instance of {@link ExternalHierarchy }
   */
  public ExternalHierarchy createExternalHierarchy() {
    return new ExternalHierarchy();
  }

  /**
   * Create an instance of {@link LeveledHierarchy }
   */
  public LeveledHierarchy createLeveledHierarchy() {
    return new LeveledHierarchy();
  }

  /**
   * Create an instance of {@link Levels }
   */
  public Levels createLevels() {
    return new Levels();
  }

  /**
   * Create an instance of {@link Level }
   */
  public Level createLevel() {
    return new Level();
  }

}
