/*
 * Copyright (c) 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, v2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-FileCopyrightText: 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.sap.ndb.datamodelgraph;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * For defining a variable
 *
 *
 * <p>Java class for EdgeVariable complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EdgeVariable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/DataModelGraph.ecore}Variable"&gt;
 *       &lt;attribute name="sourceVariable" use="required" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *       &lt;attribute name="targetVariable" use="required" type="{http://www.sap.com/ndb/BaseModelBase.ecore}DbName" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EdgeVariable")
@XmlSeeAlso({
    PathVariable.class
})
public class EdgeVariable
    extends Variable {

  @XmlAttribute(name = "sourceVariable", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String sourceVariable;
  @XmlAttribute(name = "targetVariable", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String targetVariable;

  /**
   * Gets the value of the sourceVariable property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getSourceVariable() {
    return sourceVariable;
  }

  /**
   * Sets the value of the sourceVariable property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSourceVariable(String value) {
    this.sourceVariable = value;
  }

  /**
   * Gets the value of the targetVariable property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTargetVariable() {
    return targetVariable;
  }

  /**
   * Sets the value of the targetVariable property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTargetVariable(String value) {
    this.targetVariable = value;
  }

}
