/*
 * Copyright (c) 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, v2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-FileCopyrightText: 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.sap.ndb.datamodelgraph;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GraphAction.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GraphAction"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="PATTERN_MATCHING"/&gt;
 *     &lt;enumeration value="SCRIPT_PATTERN_MATCHING"/&gt;
 *     &lt;enumeration value="GET_NEIGHBORHOOD"/&gt;
 *     &lt;enumeration value="GET_SHORTEST_PATHS_ONE_TO_ALL"/&gt;
 *     &lt;enumeration value="GET_SHORTEST_PATHS_ONE_TO_ONE"/&gt;
 *     &lt;enumeration value="GET_STRONGLY_CONNECTED_COMPONENTS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "GraphAction")
@XmlEnum
public enum GraphAction {

  PATTERN_MATCHING,
  SCRIPT_PATTERN_MATCHING,
  GET_NEIGHBORHOOD,
  GET_SHORTEST_PATHS_ONE_TO_ALL,
  GET_SHORTEST_PATHS_ONE_TO_ONE,
  GET_STRONGLY_CONNECTED_COMPONENTS;

  public static GraphAction fromValue(String v) {
    return valueOf(v);
  }

  public String value() {
    return name();
  }

}
