/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.ide;

import com.sap.xsk.models.hdbdd.ide.AbstractModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ModelIdeModule extends AbstractModelIdeModule {
}
