/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbsequence.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.sap.xsk.models.hdbsequence.HdbSequenceRuntimeModule;
import com.sap.xsk.models.hdbsequence.HdbSequenceStandaloneSetup;
import com.sap.xsk.models.hdbsequence.ide.HdbSequenceIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HdbSequenceIdeSetup extends HdbSequenceStandaloneSetup {
  @Override
  public Injector createInjector() {
    HdbSequenceRuntimeModule _hdbSequenceRuntimeModule = new HdbSequenceRuntimeModule();
    HdbSequenceIdeModule _hdbSequenceIdeModule = new HdbSequenceIdeModule();
    return Guice.createInjector(Modules2.mixin(_hdbSequenceRuntimeModule, _hdbSequenceIdeModule));
  }
}
