/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.web;

import com.google.inject.Injector;
import com.sap.xsk.models.hdbdd.ModelStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class ModelWebSetup extends ModelStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from ModelIdeModule to Module"
      + "\nType mismatch: cannot convert from ModelWebModule to Module");
  }
}
