/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbti.myHdbti;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isTable <em>Table</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getTableValue <em>Table Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isSchema <em>Schema</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getSchemaValue <em>Schema Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isFile <em>File</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getFileValue <em>File Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDelimField <em>Delim Field</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDelimFieldValue <em>Delim Field Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isHeader <em>Header</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getHeaderValue <em>Header Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isKeys <em>Keys</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getHeaderValues <em>Header Values</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDelimEnclosing <em>Delim Enclosing</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDelimEnclosingValue <em>Delim Enclosing Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDistinguishEmptyFromNull <em>Distinguish Empty From Null</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDistinguishEmptyFromNullValue <em>Distinguish Empty From Null Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isUseHeaderNames <em>Use Header Names</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getUseHeaderNamesValue <em>Use Header Names Value</em>}</li>
 * </ul>
 *
 * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig()
 * @model
 * @generated
 */
public interface ImportConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Table</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' attribute.
   * @see #setTable(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_Table()
   * @model
   * @generated
   */
  boolean isTable();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isTable <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' attribute.
   * @see #isTable()
   * @generated
   */
  void setTable(boolean value);

  /**
   * Returns the value of the '<em><b>Table Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Table Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Value</em>' attribute.
   * @see #setTableValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_TableValue()
   * @model
   * @generated
   */
  String getTableValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getTableValue <em>Table Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table Value</em>' attribute.
   * @see #getTableValue()
   * @generated
   */
  void setTableValue(String value);

  /**
   * Returns the value of the '<em><b>Schema</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schema</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema</em>' attribute.
   * @see #setSchema(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_Schema()
   * @model
   * @generated
   */
  boolean isSchema();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isSchema <em>Schema</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema</em>' attribute.
   * @see #isSchema()
   * @generated
   */
  void setSchema(boolean value);

  /**
   * Returns the value of the '<em><b>Schema Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schema Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema Value</em>' attribute.
   * @see #setSchemaValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_SchemaValue()
   * @model
   * @generated
   */
  String getSchemaValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getSchemaValue <em>Schema Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema Value</em>' attribute.
   * @see #getSchemaValue()
   * @generated
   */
  void setSchemaValue(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_File()
   * @model
   * @generated
   */
  boolean isFile();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #isFile()
   * @generated
   */
  void setFile(boolean value);

  /**
   * Returns the value of the '<em><b>File Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>File Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Value</em>' attribute.
   * @see #setFileValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_FileValue()
   * @model
   * @generated
   */
  String getFileValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getFileValue <em>File Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File Value</em>' attribute.
   * @see #getFileValue()
   * @generated
   */
  void setFileValue(String value);

  /**
   * Returns the value of the '<em><b>Delim Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delim Field</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delim Field</em>' attribute.
   * @see #setDelimField(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DelimField()
   * @model
   * @generated
   */
  boolean isDelimField();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDelimField <em>Delim Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delim Field</em>' attribute.
   * @see #isDelimField()
   * @generated
   */
  void setDelimField(boolean value);

  /**
   * Returns the value of the '<em><b>Delim Field Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delim Field Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delim Field Value</em>' attribute.
   * @see #setDelimFieldValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DelimFieldValue()
   * @model
   * @generated
   */
  String getDelimFieldValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDelimFieldValue <em>Delim Field Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delim Field Value</em>' attribute.
   * @see #getDelimFieldValue()
   * @generated
   */
  void setDelimFieldValue(String value);

  /**
   * Returns the value of the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' attribute.
   * @see #setHeader(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_Header()
   * @model
   * @generated
   */
  boolean isHeader();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isHeader <em>Header</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' attribute.
   * @see #isHeader()
   * @generated
   */
  void setHeader(boolean value);

  /**
   * Returns the value of the '<em><b>Header Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header Value</em>' attribute.
   * @see #setHeaderValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_HeaderValue()
   * @model
   * @generated
   */
  String getHeaderValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getHeaderValue <em>Header Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header Value</em>' attribute.
   * @see #getHeaderValue()
   * @generated
   */
  void setHeaderValue(String value);

  /**
   * Returns the value of the '<em><b>Keys</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keys</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' attribute.
   * @see #setKeys(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_Keys()
   * @model
   * @generated
   */
  boolean isKeys();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isKeys <em>Keys</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keys</em>' attribute.
   * @see #isKeys()
   * @generated
   */
  void setKeys(boolean value);

  /**
   * Returns the value of the '<em><b>Header Values</b></em>' containment reference list.
   * The list contents are of type {@link com.sap.xsk.models.hdbti.myHdbti.GroupType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Header Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header Values</em>' containment reference list.
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_HeaderValues()
   * @model containment="true"
   * @generated
   */
  EList<GroupType> getHeaderValues();

  /**
   * Returns the value of the '<em><b>Delim Enclosing</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delim Enclosing</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delim Enclosing</em>' attribute.
   * @see #setDelimEnclosing(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DelimEnclosing()
   * @model
   * @generated
   */
  boolean isDelimEnclosing();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDelimEnclosing <em>Delim Enclosing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delim Enclosing</em>' attribute.
   * @see #isDelimEnclosing()
   * @generated
   */
  void setDelimEnclosing(boolean value);

  /**
   * Returns the value of the '<em><b>Delim Enclosing Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delim Enclosing Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delim Enclosing Value</em>' attribute.
   * @see #setDelimEnclosingValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DelimEnclosingValue()
   * @model
   * @generated
   */
  String getDelimEnclosingValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDelimEnclosingValue <em>Delim Enclosing Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delim Enclosing Value</em>' attribute.
   * @see #getDelimEnclosingValue()
   * @generated
   */
  void setDelimEnclosingValue(String value);

  /**
   * Returns the value of the '<em><b>Distinguish Empty From Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distinguish Empty From Null</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distinguish Empty From Null</em>' attribute.
   * @see #setDistinguishEmptyFromNull(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DistinguishEmptyFromNull()
   * @model
   * @generated
   */
  boolean isDistinguishEmptyFromNull();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isDistinguishEmptyFromNull <em>Distinguish Empty From Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distinguish Empty From Null</em>' attribute.
   * @see #isDistinguishEmptyFromNull()
   * @generated
   */
  void setDistinguishEmptyFromNull(boolean value);

  /**
   * Returns the value of the '<em><b>Distinguish Empty From Null Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distinguish Empty From Null Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distinguish Empty From Null Value</em>' attribute.
   * @see #setDistinguishEmptyFromNullValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_DistinguishEmptyFromNullValue()
   * @model
   * @generated
   */
  String getDistinguishEmptyFromNullValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getDistinguishEmptyFromNullValue <em>Distinguish Empty From Null Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distinguish Empty From Null Value</em>' attribute.
   * @see #getDistinguishEmptyFromNullValue()
   * @generated
   */
  void setDistinguishEmptyFromNullValue(String value);

  /**
   * Returns the value of the '<em><b>Use Header Names</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Header Names</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Header Names</em>' attribute.
   * @see #setUseHeaderNames(boolean)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_UseHeaderNames()
   * @model
   * @generated
   */
  boolean isUseHeaderNames();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#isUseHeaderNames <em>Use Header Names</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use Header Names</em>' attribute.
   * @see #isUseHeaderNames()
   * @generated
   */
  void setUseHeaderNames(boolean value);

  /**
   * Returns the value of the '<em><b>Use Header Names Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Header Names Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Header Names Value</em>' attribute.
   * @see #setUseHeaderNamesValue(String)
   * @see com.sap.xsk.models.hdbti.myHdbti.MyHdbtiPackage#getImportConfig_UseHeaderNamesValue()
   * @model
   * @generated
   */
  String getUseHeaderNamesValue();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbti.myHdbti.ImportConfig#getUseHeaderNamesValue <em>Use Header Names Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use Header Names Value</em>' attribute.
   * @see #getUseHeaderNamesValue()
   * @generated
   */
  void setUseHeaderNamesValue(String value);

} // ImportConfig
