/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.hdbDD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getReferenceType <em>Reference Type</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntity <em>Field Reference Entity</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntityLocalId <em>Field Reference Entity Local Id</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntityForeignId <em>Field Reference Entity Foreign Id</em>}</li>
 * </ul>
 *
 * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getFieldReference()
 * @model
 * @generated
 */
public interface FieldReference extends Field
{
  /**
   * Returns the value of the '<em><b>Reference Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Type</em>' attribute.
   * @see #setReferenceType(String)
   * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getFieldReference_ReferenceType()
   * @model
   * @generated
   */
  String getReferenceType();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getReferenceType <em>Reference Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Type</em>' attribute.
   * @see #getReferenceType()
   * @generated
   */
  void setReferenceType(String value);

  /**
   * Returns the value of the '<em><b>Field Reference Entity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field Reference Entity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Reference Entity</em>' attribute.
   * @see #setFieldReferenceEntity(String)
   * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getFieldReference_FieldReferenceEntity()
   * @model
   * @generated
   */
  String getFieldReferenceEntity();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntity <em>Field Reference Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Reference Entity</em>' attribute.
   * @see #getFieldReferenceEntity()
   * @generated
   */
  void setFieldReferenceEntity(String value);

  /**
   * Returns the value of the '<em><b>Field Reference Entity Local Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field Reference Entity Local Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Reference Entity Local Id</em>' attribute.
   * @see #setFieldReferenceEntityLocalId(String)
   * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getFieldReference_FieldReferenceEntityLocalId()
   * @model
   * @generated
   */
  String getFieldReferenceEntityLocalId();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntityLocalId <em>Field Reference Entity Local Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Reference Entity Local Id</em>' attribute.
   * @see #getFieldReferenceEntityLocalId()
   * @generated
   */
  void setFieldReferenceEntityLocalId(String value);

  /**
   * Returns the value of the '<em><b>Field Reference Entity Foreign Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field Reference Entity Foreign Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Reference Entity Foreign Id</em>' attribute.
   * @see #setFieldReferenceEntityForeignId(String)
   * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getFieldReference_FieldReferenceEntityForeignId()
   * @model
   * @generated
   */
  String getFieldReferenceEntityForeignId();

  /**
   * Sets the value of the '{@link com.sap.xsk.models.hdbdd.hdbDD.FieldReference#getFieldReferenceEntityForeignId <em>Field Reference Entity Foreign Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Reference Entity Foreign Id</em>' attribute.
   * @see #getFieldReferenceEntityForeignId()
   * @generated
   */
  void setFieldReferenceEntityForeignId(String value);

} // FieldReference
