/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.hdbDD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sap.xsk.models.hdbdd.hdbDD.HdbDDPackage#getSchema()
 * @model
 * @generated
 */
public interface Schema extends Type
{
} // Schema
