/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbti.validation;

import com.sap.xsk.models.hdbti.validation.AbstractHdbtiValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HdbtiValidator extends AbstractHdbtiValidator {
}
