/*
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbtable.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractHdbTableValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.sap.xsk.models.hdbtable.hdbTable.HdbTablePackage.eINSTANCE);
		return result;
	}
}
