{{- if ne .Values.namespace.create false }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ required "Missing namespace" .Values.namespace.name }}
{{- end }}
---
{{- if .Values.hana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hana.secretName }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES: HANA
  DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT: HANA
  DIRIGIBLE_DATABASE_NAMES_CASE_SENSITIVE: "true"
  DIRIGIBLE_DATABASE_PROVIDER: custom
  DIRIGIBLE_FLOWABLE_USE_DEFAULT_DATABASE: "false"
  DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE: "false"
  DIRIGIBLE_SCHEDULER_DATABASE_DRIVER: com.sap.db.jdbc.Driver
  DIRIGIBLE_SCHEDULER_DATABASE_PASSWORD: {{ required "Missing HANA password" .Values.hana.password }}
  DIRIGIBLE_SCHEDULER_DATABASE_URL: jdbc:sap://{{ required "Missing HANA url" .Values.hana.url }}/?encrypt=true&validateCertificate=false
  DIRIGIBLE_SCHEDULER_DATABASE_USER: {{ required "Missing HANA username" .Values.hana.username }}
  HANA_DRIVER: com.sap.db.jdbc.Driver
  HANA_PASSWORD: {{ required "Missing HANA password" .Values.hana.password }}
  HANA_URL: jdbc:sap://{{ required "Missing HANA url" .Values.hana.url }}/?encrypt=true&validateCertificate=false
  HANA_USERNAME: {{ required "Missing HANA username" .Values.hana.username }}
---
{{- else }}
{{- if or .Values.hana.username .Values.hana.password .Values.hana.url }}
{{ required "Missing HANA set configuration 'hana.enabled=true' " .Values.hana.enabled }}
{{- end }}
{{- end }}
{{- if .Values.application.fastBootstrap }}
apiVersion: v1
kind: Secret
metadata:
  name: fast-boostrap-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DIRIGIBLE_JOB_DEFAULT_TIMEOUT: "1"
  DIRIGIBLE_SCHEDULER_MEMORY_STORE: "true"
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xsk.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xsk.labels" . | nindent 4 }}
spec:
  replicas: {{ required "Missing replica count" .Values.replicaCount }}
  strategy:
    type: {{ required "Missing deployment strategy type" .Values.deployment.strategyType }}
  selector:
    matchLabels:
      {{- include "xsk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xsk.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "xsk.serviceAccountName" . }}
      containers:
        - name: {{ required "Missing chart name" .Chart.Name }}
          envFrom:
          {{- if .Values.hana.enabled }}
            - secretRef:
                name: {{ required "Missing HANA secret name" .Values.hana.secretName }}
          {{- end }}
          {{- if .Values.application.fastBootstrap }}
            - secretRef:
                name: fast-boostrap-secret
          {{- end }}
          env:
            {{- if .Values.kyma.enabled }}
            - name: DIRIGIBLE_HOST
              value: https://{{ required "Missing release name" .Release.Name }}.{{ required "Missing Kyma host" .Values.kyma.host }}
            - name: SERVER_MAXHTTPHEADERSIZE
              value: "{{ required "Missing Kyma server maximum http header size" .Values.kyma.serverMaxHttpHeaderSize }}"
            {{- end }}
            {{- if .Values.application.homeUrl }}
            - name: DIRIGIBLE_HOME_URL
              value: {{ required "Missing application home url" .Values.application.homeUrl }}
            {{- end }}
          {{- if .Values.application.image }}
          image: {{ required "Missing application image" .Values.application.image }}                    
          {{- else if .Values.kyma.enabled }}
          image: dirigiblelabs/xsk-kyma:latest
          {{- else }}
          image: dirigiblelabs/xsk
          {{- end }}  
          imagePullPolicy: {{ required "Missing application image pull policy" .Values.application.imagePullPolicy }}
          volumeMounts:
          - name: {{ required "Missing volume mounts name" .Values.deployment.volumeMountsName }}
            mountPath: {{ required "Missing volume mounts path" .Values.deployment.volumeMountsMountPath }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:  
            tcpSocket:
              port: {{ required "Missing deployment readiness probe http get port" .Values.deployment.readinessProbeHttpGetPort }}
            initialDelaySeconds: {{ required "Missing deployment readiness initial delay seconds" .Values.deployment.readinessProbeInitialDelaySeconds }}
            periodSeconds: {{ required "Missing deployment readiness probe period second" .Values.deployment.readinessProbePeriodSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbeHttpGetPort}}
            initialDelaySeconds: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbeInitialDelaySeconds}}
            periodSeconds: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbePeriodSeconds}}
      {{- if .Values.persistentVolumeClaim.enabled }}
      volumes:
      - name: {{ required "Missing volume mounts name" .Values.deployment.volumesName }}
        persistentVolumeClaim:
          claimName: {{ required "Missing volume mounts name" .Values.deployment.volumespersistentVolumeClaimClaimName }}
      {{- end }}
---
{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "Missing persistent volume claim name" .Values.persistentVolumeClaim.name }}
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
spec:
  accessModes:
  - {{ required "Missing persistent volume claim access mode" .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ required "Missing persistent volume claim resource storage" .Values.persistentVolumeClaim.resourcesStorage }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xsk.fullname" . }}
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
  labels:
    {{- include "xsk.labels" . | nindent 4 }}
spec:
  type: {{ required "Missing service type" .Values.service.type }}
  ports:
    - port: {{ required "Missing service port" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xsk.selectorLabels" . | nindent 4 }}
---
{{- if .Values.kyma.enabled }}
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "xsk.fullname" . }}
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: {{ required "Missing release name" .Release.Name }}
    name: {{ include "xsk.fullname" . }}
    port: 8080
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-{{ include "xsk.fullname" . }}
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServiceClassRef:
    name: xsuaa
  clusterServicePlanExternalName: broker
  parameters:
    xsappname: {{ include "xsk.fullname" . }}-xsuaa
    oauth2-configuration:
      redirect-uris:
      - https://{{ .Release.Name }}.{{ required "Missing Kyma host" .Values.kyma.host }}
      token-validity: 7200
    role-collections:
    {{- toYaml .Values.kyma.roleCollections | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: XSK {{ . }}
      name: xsk-{{ . }}
      role-template-references:
      - $XSAPPNAME.{{ . }}  
    {{- end }}
    {{- end }}
    role-templates:
    {{- toYaml .Values.kyma.roleTemplates | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: {{ . }}  related roles
      name: {{ . }} 
      scope-references:
      - $XSAPPNAME.{{ . }}
    {{- end }}
    {{- end }}
    scopes:
    {{- toYaml .Values.kyma.scopes | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: {{ . }} scope
      name: $XSAPPNAME.{{ . }}
    {{- end }}
    {{- end }}
      
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-{{ include "xsk.fullname" . }}-binding
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
spec:
  instanceRef:
    name: xsuaa-{{ include "xsk.fullname" . }}
  parameters: {}
  secretName: xsuaa-{{ include "xsk.fullname" . }}-binding
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-{{ include "xsk.fullname" . }}-usage
  namespace: {{ required "Missing namespace" .Values.namespace.name }}
spec:
  parameters:
    envPrefix:
      name: ""
  serviceBindingRef:
    name: xsuaa-{{ include "xsk.fullname" . }}-binding
  usedBy:
    kind: deployment
    name: {{ include "xsk.fullname" . }}
{{- else }}
{{- if or .Values.kyma.host }}
{{ required "Missing Kyma set configuration 'kyma.enabled=true' " .Values.kyma.enabled }}
{{- end }}
{{- end }}

