{{- if .Values.hana.enabled }}
{{- if .Values.hana.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hana.secretName }}
type: Opaque
stringData:
  DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES: HANA
  DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT: HANA
  DIRIGIBLE_DATABASE_PROVIDER: custom
  HANA_DRIVER: com.sap.db.jdbc.Driver
  HANA_PASSWORD: {{ required "Missing HANA password" .Values.hana.password }}
  HANA_URL: {{ required "Missing HANA url" .Values.hana.url }}
  HANA_USERNAME: {{ required "Missing HANA username" .Values.hana.username }}
---
{{- end }}
{{- else }}
{{- if or .Values.hana.username .Values.hana.password .Values.hana.url }}
{{ required "Missing HANA set configuration 'hana.enabled=true' " .Values.hana.enabled }}
{{- end }}
{{- end }}
{{- if .Values.application.privateDockerRegistry }}
{{- if .Values.application.privateDockerRegistrySecret }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: {{ required "Missing docker secret name" .Values.application.dockerSecretName }}
type: kubernetes.io/dockerconfigjson 
---
{{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xsk.fullname" . }}
  labels:
    {{- include "xsk.labels" . | nindent 4 }}
spec:
  replicas: {{ required "Missing replica count" .Values.replicaCount }}
  strategy:
    type: {{ required "Missing deployment strategy type" .Values.deployment.strategyType }}
  selector:
    matchLabels:
      {{- include "xsk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xsk.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "xsk.serviceAccountName" . }}
      containers:
        - name: {{ required "Missing chart name" .Chart.Name }}
          envFrom:
          {{- if .Values.hana.enabled }}
            - secretRef:
                name: {{ required "Missing HANA secret name" .Values.hana.secretName }}
          {{- end }}
          {{- if .Values.kyma.enabled }}
            - secretRef:
                name: xsuaa-{{ include "xsk.fullname" . }}-binding
          {{- end }}
          {{- if .Values.kyma.destinationServiceEnabled }}
            - secretRef:
                name: destination-{{ default  .Release.Name  .Values.kyma.destinationServiceBindingSecretName }}-binding
              prefix: destination_
          {{- end }}
          env:
            {{- if .Values.kyma.enabled }}
            - name: DIRIGIBLE_HOST
              value: https://{{ required "Missing release name" .Release.Name }}.{{ required "Missing Kyma host" .Values.kyma.host }}
            - name: SERVER_MAXHTTPHEADERSIZE
              value: "{{ required "Missing Kyma server maximum http header size" .Values.kyma.serverMaxHttpHeaderSize }}"
            {{- end }}
            {{- if .Values.application.homeUrl }}
            - name: DIRIGIBLE_HOME_URL
              value: {{ required "Missing application home url" .Values.application.homeUrl }}
            {{- end }}
          {{- if .Values.application.image }}
          image: {{ required "Missing application image" .Values.application.image }}                    
          {{- else if .Values.kyma.enabled }}
          image: dirigiblelabs/xsk-kyma:{{ required "Missing chart version" .Chart.Version }}
          {{- else }}
          image: dirigiblelabs/xsk:{{ required "Missing chart version" .Chart.Version }}
          {{- end }}  
          imagePullPolicy: {{ required "Missing application image pull policy" .Values.application.imagePullPolicy }}
          {{- if .Values.persistentVolumeClaim.enabled }}
          volumeMounts:
          - name: {{ required "Missing volume mounts name" .Values.deployment.volumeMountsName }}
            mountPath: {{ required "Missing volume mounts path" .Values.deployment.volumeMountsMountPath }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.deployment.resourcesEnabled }}
          resources:
            requests:
              memory: {{ .Values.deployment.resourcesRequestsMemory }}
              cpu: {{ .Values.deployment.resourcesRequestsCpu }}
            limits:
              memory: {{ .Values.deployment.resourcesLimitsMemory }}
              cpu: {{ .Values.deployment.resourcesLimitsCpu }}
          {{- end }}
          readinessProbe:  
            tcpSocket:
              port: {{ required "Missing deployment readiness probe http get port" .Values.deployment.readinessProbeHttpGetPort }}
            initialDelaySeconds: {{ required "Missing deployment readiness initial delay seconds" .Values.deployment.readinessProbeInitialDelaySeconds }}
            periodSeconds: {{ required "Missing deployment readiness probe period second" .Values.deployment.readinessProbePeriodSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbeHttpGetPort}}
            initialDelaySeconds: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbeInitialDelaySeconds}}
            periodSeconds: {{ required "Missing deployment liveness probe http get port" .Values.deployment.LivenessProbePeriodSeconds}}
      {{- if .Values.application.privateDockerRegistry }}
      imagePullSecrets:
      - name: {{ required "Missing docker secret name" .Values.application.dockerSecretName }}
      {{- end }}
      {{- if .Values.persistentVolumeClaim.enabled }}
      volumes:
      - name: {{ required "Missing volume mounts name" .Values.deployment.volumesName }}
        persistentVolumeClaim:
          claimName: {{ required "Missing volume mounts name" .Values.deployment.volumespersistentVolumeClaimClaimName }}
      {{- end }}
---
{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "Missing persistent volume claim name" .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
  - {{ required "Missing persistent volume claim access mode" .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ required "Missing persistent volume claim resource storage" .Values.persistentVolumeClaim.resourcesStorage }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xsk.fullname" . }}
  labels:
    {{- include "xsk.labels" . | nindent 4 }}
spec:
  type: {{ required "Missing service type" .Values.service.type }}
  ports:
    - port: {{ required "Missing service port" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xsk.selectorLabels" . | nindent 4 }}
---
{{- if .Values.kyma.enabled }}
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "xsk.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: {{ required "Missing release name" .Release.Name }}
    name: {{ include "xsk.fullname" . }}
    port: 8080
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: xsuaa-{{ include "xsk.fullname" . }}
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  externalName: {{ include "xsk.fullname" . }}-service-instance
  parameters:
    xsappname: {{ include "xsk.fullname" . }}-xsuaa
    oauth2-configuration:
      redirect-uris:
      - https://{{ .Release.Name }}.{{ required "Missing Kyma host" .Values.kyma.host }}
      token-validity: 7200
    role-collections:
    {{- include "xsk.roleCollections" . | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: XSK {{ . }}
      name: xsk-{{ . }}
      role-template-references:
      - $XSAPPNAME.{{ . }}  
    {{- end }}
    {{- end }}
    role-templates:
    {{- include "xsk.roleTemplates" . | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: {{ . }}  related roles
      name: {{ . }} 
      scope-references:
      - $XSAPPNAME.{{ . }}
    {{- end }}
    {{- end }}
    scopes:
    {{- include "xsk.scopes" . | nindent 4 }}
    {{- if .Values.kyma.addRoles }}
    {{ range .Values.kyma.roles }}
    - description: {{ . }} scope
      name: $XSAPPNAME.{{ . }}
    {{- end }}
    {{- end }}
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: xsuaa-{{ include "xsk.fullname" . }}-binding
spec:
  serviceInstanceName: xsuaa-{{ include "xsk.fullname" . }}
  externalName: {{ include "xsk.fullname" . }}-binding-external
  secretName: xsuaa-{{ include "xsk.fullname" . }}-binding
  parameters: {}
---
{{- if .Values.kyma.destinationServiceEnabled }}
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: destination-{{ default .Release.Name .Values.kyma.destinationServiceInstanceName }}
spec:
  serviceOfferingName: {{ required "Missing destination service instance offering name" .Values.kyma.destinationServiceInstanceOfferingName }}
  servicePlanName: {{ required "Missing destination service instance plan name" .Values.kyma.destinationServiceInstancePlanName }}
  externalName: destination-{{ default .Release.Name .Values.kyma.destinationServiceInstanceExternalName }}
  parameters: {{ required "Missing destination service instance parameters" .Values.kyma.destinationServiceInstanceParameters }}
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: destination-{{ default .Release.Name .Values.kyma.destinationServiceBindingName }}-binding
spec:
  serviceInstanceName: destination-{{ default .Release.Name .Values.kyma.destinationServiceInstanceName }}
  externalName: destination-{{ default  .Release.Name .Values.kyma.destinationServiceBindingExternalName }}-binding
  secretName: destination-{{ default  .Release.Name  .Values.kyma.destinationServiceBindingSecretName }}-binding
  parameters: {{ required "Missing destination service binding parameters" .Values.kyma.destinationServiceBindingParameters }}
{{- end }}
{{- else }}
{{- if or .Values.kyma.host }}
{{ required "Missing Kyma set configuration 'kyma.enabled=true' " .Values.kyma.enabled }}
{{- end }}
{{- end }}

