/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbsequence.hdbSequence;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.ListString#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see com.sap.xsk.models.hdbsequence.hdbSequence.HdbSequencePackage#getListString()
 * @model
 * @generated
 */
public interface ListString extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see com.sap.xsk.models.hdbsequence.hdbSequence.HdbSequencePackage#getListString_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // ListString
