/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbsequence.hdbSequence.impl;

import com.sap.xsk.models.hdbsequence.hdbSequence.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HdbSequenceFactoryImpl extends EFactoryImpl implements HdbSequenceFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static HdbSequenceFactory init()
  {
    try
    {
      HdbSequenceFactory theHdbSequenceFactory = (HdbSequenceFactory)EPackage.Registry.INSTANCE.getEFactory(HdbSequencePackage.eNS_URI);
      if (theHdbSequenceFactory != null)
      {
        return theHdbSequenceFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new HdbSequenceFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HdbSequenceFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case HdbSequencePackage.HDB_SEQUENCE_MODEL: return createHdbSequenceModel();
      case HdbSequencePackage.LIST_STRING: return createListString();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS: return createHdbSequenceElements();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HdbSequenceModel createHdbSequenceModel()
  {
    HdbSequenceModelImpl hdbSequenceModel = new HdbSequenceModelImpl();
    return hdbSequenceModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListString createListString()
  {
    ListStringImpl listString = new ListStringImpl();
    return listString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HdbSequenceElements createHdbSequenceElements()
  {
    HdbSequenceElementsImpl hdbSequenceElements = new HdbSequenceElementsImpl();
    return hdbSequenceElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HdbSequencePackage getHdbSequencePackage()
  {
    return (HdbSequencePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static HdbSequencePackage getPackage()
  {
    return HdbSequencePackage.eINSTANCE;
  }

} //HdbSequenceFactoryImpl
