# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-xsk-kyma-runtime"
    version = "#{XSKVersion}#"

[stack]
id = "com.sap.kneo.xsk"
build-image = "dirigiblelabs/buildpacks-stack-build-xsk-kyma-runtime"
run-image = "dirigiblelabs/buildpacks-stack-run-xsk-kyma-runtime"
