/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbsequence.hdbSequence.impl;

import com.sap.xsk.models.hdbsequence.hdbSequence.HdbSequenceElements;
import com.sap.xsk.models.hdbsequence.hdbSequence.HdbSequencePackage;
import com.sap.xsk.models.hdbsequence.hdbSequence.ListString;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Elements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getSchema <em>Schema</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getSchemaValue <em>Schema Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getIncrementBy <em>Increment By</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getIncrementByValue <em>Increment By Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getStartWith <em>Start With</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getStartWithValue <em>Start With Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getMaxValue <em>Max Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getMaxValueValue <em>Max Value Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getNoMaxValue <em>No Max Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getNoMaxValueValue <em>No Max Value Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getMinVlaueValue <em>Min Vlaue Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getNoMinValue <em>No Min Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getNoMinValueValue <em>No Min Value Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getCycles <em>Cycles</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getCyclesValue <em>Cycles Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getPublic <em>Public</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getPublicValue <em>Public Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getDependsOnTable <em>Depends On Table</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getDependsOnTableValue <em>Depends On Table Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getDependsOnView <em>Depends On View</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getDependsOnViewValue <em>Depends On View Value</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbsequence.hdbSequence.impl.HdbSequenceElementsImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HdbSequenceElementsImpl extends MinimalEObjectImpl.Container implements HdbSequenceElements
{
  /**
   * The default value of the '{@link #getSchema() <em>Schema</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchema()
   * @generated
   * @ordered
   */
  protected static final String SCHEMA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSchema() <em>Schema</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchema()
   * @generated
   * @ordered
   */
  protected String schema = SCHEMA_EDEFAULT;

  /**
   * The default value of the '{@link #getSchemaValue() <em>Schema Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemaValue()
   * @generated
   * @ordered
   */
  protected static final String SCHEMA_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSchemaValue() <em>Schema Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemaValue()
   * @generated
   * @ordered
   */
  protected String schemaValue = SCHEMA_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getIncrementBy() <em>Increment By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementBy()
   * @generated
   * @ordered
   */
  protected static final String INCREMENT_BY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIncrementBy() <em>Increment By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementBy()
   * @generated
   * @ordered
   */
  protected String incrementBy = INCREMENT_BY_EDEFAULT;

  /**
   * The default value of the '{@link #getIncrementByValue() <em>Increment By Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementByValue()
   * @generated
   * @ordered
   */
  protected static final int INCREMENT_BY_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIncrementByValue() <em>Increment By Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncrementByValue()
   * @generated
   * @ordered
   */
  protected int incrementByValue = INCREMENT_BY_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getStartWith() <em>Start With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWith()
   * @generated
   * @ordered
   */
  protected static final String START_WITH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStartWith() <em>Start With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWith()
   * @generated
   * @ordered
   */
  protected String startWith = START_WITH_EDEFAULT;

  /**
   * The default value of the '{@link #getStartWithValue() <em>Start With Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWithValue()
   * @generated
   * @ordered
   */
  protected static final int START_WITH_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStartWithValue() <em>Start With Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartWithValue()
   * @generated
   * @ordered
   */
  protected int startWithValue = START_WITH_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxValue() <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValue()
   * @generated
   * @ordered
   */
  protected static final String MAX_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMaxValue() <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValue()
   * @generated
   * @ordered
   */
  protected String maxValue = MAX_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxValueValue() <em>Max Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValueValue()
   * @generated
   * @ordered
   */
  protected static final int MAX_VALUE_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxValueValue() <em>Max Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxValueValue()
   * @generated
   * @ordered
   */
  protected int maxValueValue = MAX_VALUE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getNoMaxValue() <em>No Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMaxValue()
   * @generated
   * @ordered
   */
  protected static final String NO_MAX_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoMaxValue() <em>No Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMaxValue()
   * @generated
   * @ordered
   */
  protected String noMaxValue = NO_MAX_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getNoMaxValueValue() <em>No Max Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMaxValueValue()
   * @generated
   * @ordered
   */
  protected static final String NO_MAX_VALUE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoMaxValueValue() <em>No Max Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMaxValueValue()
   * @generated
   * @ordered
   */
  protected String noMaxValueValue = NO_MAX_VALUE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMinValue() <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinValue()
   * @generated
   * @ordered
   */
  protected static final String MIN_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMinValue() <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinValue()
   * @generated
   * @ordered
   */
  protected String minValue = MIN_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMinVlaueValue() <em>Min Vlaue Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinVlaueValue()
   * @generated
   * @ordered
   */
  protected static final int MIN_VLAUE_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMinVlaueValue() <em>Min Vlaue Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMinVlaueValue()
   * @generated
   * @ordered
   */
  protected int minVlaueValue = MIN_VLAUE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getNoMinValue() <em>No Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMinValue()
   * @generated
   * @ordered
   */
  protected static final String NO_MIN_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoMinValue() <em>No Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMinValue()
   * @generated
   * @ordered
   */
  protected String noMinValue = NO_MIN_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getNoMinValueValue() <em>No Min Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMinValueValue()
   * @generated
   * @ordered
   */
  protected static final String NO_MIN_VALUE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNoMinValueValue() <em>No Min Value Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNoMinValueValue()
   * @generated
   * @ordered
   */
  protected String noMinValueValue = NO_MIN_VALUE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getCycles() <em>Cycles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCycles()
   * @generated
   * @ordered
   */
  protected static final String CYCLES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCycles() <em>Cycles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCycles()
   * @generated
   * @ordered
   */
  protected String cycles = CYCLES_EDEFAULT;

  /**
   * The default value of the '{@link #getCyclesValue() <em>Cycles Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclesValue()
   * @generated
   * @ordered
   */
  protected static final String CYCLES_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCyclesValue() <em>Cycles Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclesValue()
   * @generated
   * @ordered
   */
  protected String cyclesValue = CYCLES_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getPublic() <em>Public</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublic()
   * @generated
   * @ordered
   */
  protected static final String PUBLIC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPublic() <em>Public</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublic()
   * @generated
   * @ordered
   */
  protected String public_ = PUBLIC_EDEFAULT;

  /**
   * The default value of the '{@link #getPublicValue() <em>Public Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublicValue()
   * @generated
   * @ordered
   */
  protected static final String PUBLIC_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPublicValue() <em>Public Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublicValue()
   * @generated
   * @ordered
   */
  protected String publicValue = PUBLIC_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getDependsOnTable() <em>Depends On Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnTable()
   * @generated
   * @ordered
   */
  protected static final String DEPENDS_ON_TABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependsOnTable() <em>Depends On Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnTable()
   * @generated
   * @ordered
   */
  protected String dependsOnTable = DEPENDS_ON_TABLE_EDEFAULT;

  /**
   * The default value of the '{@link #getDependsOnTableValue() <em>Depends On Table Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnTableValue()
   * @generated
   * @ordered
   */
  protected static final String DEPENDS_ON_TABLE_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependsOnTableValue() <em>Depends On Table Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnTableValue()
   * @generated
   * @ordered
   */
  protected String dependsOnTableValue = DEPENDS_ON_TABLE_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getDependsOnView() <em>Depends On View</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnView()
   * @generated
   * @ordered
   */
  protected static final String DEPENDS_ON_VIEW_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependsOnView() <em>Depends On View</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnView()
   * @generated
   * @ordered
   */
  protected String dependsOnView = DEPENDS_ON_VIEW_EDEFAULT;

  /**
   * The default value of the '{@link #getDependsOnViewValue() <em>Depends On View Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnViewValue()
   * @generated
   * @ordered
   */
  protected static final String DEPENDS_ON_VIEW_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependsOnViewValue() <em>Depends On View Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependsOnViewValue()
   * @generated
   * @ordered
   */
  protected String dependsOnViewValue = DEPENDS_ON_VIEW_VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected ListString value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HdbSequenceElementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HdbSequencePackage.Literals.HDB_SEQUENCE_ELEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSchema()
  {
    return schema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSchema(String newSchema)
  {
    String oldSchema = schema;
    schema = newSchema;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA, oldSchema, schema));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSchemaValue()
  {
    return schemaValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSchemaValue(String newSchemaValue)
  {
    String oldSchemaValue = schemaValue;
    schemaValue = newSchemaValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA_VALUE, oldSchemaValue, schemaValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIncrementBy()
  {
    return incrementBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIncrementBy(String newIncrementBy)
  {
    String oldIncrementBy = incrementBy;
    incrementBy = newIncrementBy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY, oldIncrementBy, incrementBy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIncrementByValue()
  {
    return incrementByValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIncrementByValue(int newIncrementByValue)
  {
    int oldIncrementByValue = incrementByValue;
    incrementByValue = newIncrementByValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY_VALUE, oldIncrementByValue, incrementByValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStartWith()
  {
    return startWith;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartWith(String newStartWith)
  {
    String oldStartWith = startWith;
    startWith = newStartWith;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH, oldStartWith, startWith));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStartWithValue()
  {
    return startWithValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartWithValue(int newStartWithValue)
  {
    int oldStartWithValue = startWithValue;
    startWithValue = newStartWithValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH_VALUE, oldStartWithValue, startWithValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMaxValue()
  {
    return maxValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMaxValue(String newMaxValue)
  {
    String oldMaxValue = maxValue;
    maxValue = newMaxValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE, oldMaxValue, maxValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getMaxValueValue()
  {
    return maxValueValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMaxValueValue(int newMaxValueValue)
  {
    int oldMaxValueValue = maxValueValue;
    maxValueValue = newMaxValueValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE_VALUE, oldMaxValueValue, maxValueValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNoMaxValue()
  {
    return noMaxValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNoMaxValue(String newNoMaxValue)
  {
    String oldNoMaxValue = noMaxValue;
    noMaxValue = newNoMaxValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE, oldNoMaxValue, noMaxValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNoMaxValueValue()
  {
    return noMaxValueValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNoMaxValueValue(String newNoMaxValueValue)
  {
    String oldNoMaxValueValue = noMaxValueValue;
    noMaxValueValue = newNoMaxValueValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE_VALUE, oldNoMaxValueValue, noMaxValueValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMinValue()
  {
    return minValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMinValue(String newMinValue)
  {
    String oldMinValue = minValue;
    minValue = newMinValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VALUE, oldMinValue, minValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getMinVlaueValue()
  {
    return minVlaueValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMinVlaueValue(int newMinVlaueValue)
  {
    int oldMinVlaueValue = minVlaueValue;
    minVlaueValue = newMinVlaueValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VLAUE_VALUE, oldMinVlaueValue, minVlaueValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNoMinValue()
  {
    return noMinValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNoMinValue(String newNoMinValue)
  {
    String oldNoMinValue = noMinValue;
    noMinValue = newNoMinValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE, oldNoMinValue, noMinValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNoMinValueValue()
  {
    return noMinValueValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNoMinValueValue(String newNoMinValueValue)
  {
    String oldNoMinValueValue = noMinValueValue;
    noMinValueValue = newNoMinValueValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE_VALUE, oldNoMinValueValue, noMinValueValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCycles()
  {
    return cycles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCycles(String newCycles)
  {
    String oldCycles = cycles;
    cycles = newCycles;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES, oldCycles, cycles));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCyclesValue()
  {
    return cyclesValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCyclesValue(String newCyclesValue)
  {
    String oldCyclesValue = cyclesValue;
    cyclesValue = newCyclesValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES_VALUE, oldCyclesValue, cyclesValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPublic()
  {
    return public_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPublic(String newPublic)
  {
    String oldPublic = public_;
    public_ = newPublic;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC, oldPublic, public_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPublicValue()
  {
    return publicValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPublicValue(String newPublicValue)
  {
    String oldPublicValue = publicValue;
    publicValue = newPublicValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC_VALUE, oldPublicValue, publicValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependsOnTable()
  {
    return dependsOnTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependsOnTable(String newDependsOnTable)
  {
    String oldDependsOnTable = dependsOnTable;
    dependsOnTable = newDependsOnTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE, oldDependsOnTable, dependsOnTable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependsOnTableValue()
  {
    return dependsOnTableValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependsOnTableValue(String newDependsOnTableValue)
  {
    String oldDependsOnTableValue = dependsOnTableValue;
    dependsOnTableValue = newDependsOnTableValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE_VALUE, oldDependsOnTableValue, dependsOnTableValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependsOnView()
  {
    return dependsOnView;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependsOnView(String newDependsOnView)
  {
    String oldDependsOnView = dependsOnView;
    dependsOnView = newDependsOnView;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW, oldDependsOnView, dependsOnView));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependsOnViewValue()
  {
    return dependsOnViewValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependsOnViewValue(String newDependsOnViewValue)
  {
    String oldDependsOnViewValue = dependsOnViewValue;
    dependsOnViewValue = newDependsOnViewValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW_VALUE, oldDependsOnViewValue, dependsOnViewValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListString getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(ListString newValue, NotificationChain msgs)
  {
    ListString oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(ListString newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE:
        return basicSetValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA:
        return getSchema();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA_VALUE:
        return getSchemaValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY:
        return getIncrementBy();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY_VALUE:
        return getIncrementByValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH:
        return getStartWith();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH_VALUE:
        return getStartWithValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE:
        return getMaxValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE_VALUE:
        return getMaxValueValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE:
        return getNoMaxValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE_VALUE:
        return getNoMaxValueValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VALUE:
        return getMinValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VLAUE_VALUE:
        return getMinVlaueValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE:
        return getNoMinValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE_VALUE:
        return getNoMinValueValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES:
        return getCycles();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES_VALUE:
        return getCyclesValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC:
        return getPublic();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC_VALUE:
        return getPublicValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE:
        return getDependsOnTable();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE_VALUE:
        return getDependsOnTableValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW:
        return getDependsOnView();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW_VALUE:
        return getDependsOnViewValue();
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA:
        setSchema((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA_VALUE:
        setSchemaValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY:
        setIncrementBy((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY_VALUE:
        setIncrementByValue((Integer)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH:
        setStartWith((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH_VALUE:
        setStartWithValue((Integer)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE:
        setMaxValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE_VALUE:
        setMaxValueValue((Integer)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE:
        setNoMaxValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE_VALUE:
        setNoMaxValueValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VALUE:
        setMinValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VLAUE_VALUE:
        setMinVlaueValue((Integer)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE:
        setNoMinValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE_VALUE:
        setNoMinValueValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES:
        setCycles((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES_VALUE:
        setCyclesValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC:
        setPublic((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC_VALUE:
        setPublicValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE:
        setDependsOnTable((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE_VALUE:
        setDependsOnTableValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW:
        setDependsOnView((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW_VALUE:
        setDependsOnViewValue((String)newValue);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE:
        setValue((ListString)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA:
        setSchema(SCHEMA_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA_VALUE:
        setSchemaValue(SCHEMA_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY:
        setIncrementBy(INCREMENT_BY_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY_VALUE:
        setIncrementByValue(INCREMENT_BY_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH:
        setStartWith(START_WITH_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH_VALUE:
        setStartWithValue(START_WITH_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE:
        setMaxValue(MAX_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE_VALUE:
        setMaxValueValue(MAX_VALUE_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE:
        setNoMaxValue(NO_MAX_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE_VALUE:
        setNoMaxValueValue(NO_MAX_VALUE_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VALUE:
        setMinValue(MIN_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VLAUE_VALUE:
        setMinVlaueValue(MIN_VLAUE_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE:
        setNoMinValue(NO_MIN_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE_VALUE:
        setNoMinValueValue(NO_MIN_VALUE_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES:
        setCycles(CYCLES_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES_VALUE:
        setCyclesValue(CYCLES_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC:
        setPublic(PUBLIC_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC_VALUE:
        setPublicValue(PUBLIC_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE:
        setDependsOnTable(DEPENDS_ON_TABLE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE_VALUE:
        setDependsOnTableValue(DEPENDS_ON_TABLE_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW:
        setDependsOnView(DEPENDS_ON_VIEW_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW_VALUE:
        setDependsOnViewValue(DEPENDS_ON_VIEW_VALUE_EDEFAULT);
        return;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE:
        setValue((ListString)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA:
        return SCHEMA_EDEFAULT == null ? schema != null : !SCHEMA_EDEFAULT.equals(schema);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__SCHEMA_VALUE:
        return SCHEMA_VALUE_EDEFAULT == null ? schemaValue != null : !SCHEMA_VALUE_EDEFAULT.equals(schemaValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY:
        return INCREMENT_BY_EDEFAULT == null ? incrementBy != null : !INCREMENT_BY_EDEFAULT.equals(incrementBy);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__INCREMENT_BY_VALUE:
        return incrementByValue != INCREMENT_BY_VALUE_EDEFAULT;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH:
        return START_WITH_EDEFAULT == null ? startWith != null : !START_WITH_EDEFAULT.equals(startWith);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__START_WITH_VALUE:
        return startWithValue != START_WITH_VALUE_EDEFAULT;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE:
        return MAX_VALUE_EDEFAULT == null ? maxValue != null : !MAX_VALUE_EDEFAULT.equals(maxValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MAX_VALUE_VALUE:
        return maxValueValue != MAX_VALUE_VALUE_EDEFAULT;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE:
        return NO_MAX_VALUE_EDEFAULT == null ? noMaxValue != null : !NO_MAX_VALUE_EDEFAULT.equals(noMaxValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MAX_VALUE_VALUE:
        return NO_MAX_VALUE_VALUE_EDEFAULT == null ? noMaxValueValue != null : !NO_MAX_VALUE_VALUE_EDEFAULT.equals(noMaxValueValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VALUE:
        return MIN_VALUE_EDEFAULT == null ? minValue != null : !MIN_VALUE_EDEFAULT.equals(minValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__MIN_VLAUE_VALUE:
        return minVlaueValue != MIN_VLAUE_VALUE_EDEFAULT;
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE:
        return NO_MIN_VALUE_EDEFAULT == null ? noMinValue != null : !NO_MIN_VALUE_EDEFAULT.equals(noMinValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__NO_MIN_VALUE_VALUE:
        return NO_MIN_VALUE_VALUE_EDEFAULT == null ? noMinValueValue != null : !NO_MIN_VALUE_VALUE_EDEFAULT.equals(noMinValueValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES:
        return CYCLES_EDEFAULT == null ? cycles != null : !CYCLES_EDEFAULT.equals(cycles);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__CYCLES_VALUE:
        return CYCLES_VALUE_EDEFAULT == null ? cyclesValue != null : !CYCLES_VALUE_EDEFAULT.equals(cyclesValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC:
        return PUBLIC_EDEFAULT == null ? public_ != null : !PUBLIC_EDEFAULT.equals(public_);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__PUBLIC_VALUE:
        return PUBLIC_VALUE_EDEFAULT == null ? publicValue != null : !PUBLIC_VALUE_EDEFAULT.equals(publicValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE:
        return DEPENDS_ON_TABLE_EDEFAULT == null ? dependsOnTable != null : !DEPENDS_ON_TABLE_EDEFAULT.equals(dependsOnTable);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_TABLE_VALUE:
        return DEPENDS_ON_TABLE_VALUE_EDEFAULT == null ? dependsOnTableValue != null : !DEPENDS_ON_TABLE_VALUE_EDEFAULT.equals(dependsOnTableValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW:
        return DEPENDS_ON_VIEW_EDEFAULT == null ? dependsOnView != null : !DEPENDS_ON_VIEW_EDEFAULT.equals(dependsOnView);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__DEPENDS_ON_VIEW_VALUE:
        return DEPENDS_ON_VIEW_VALUE_EDEFAULT == null ? dependsOnViewValue != null : !DEPENDS_ON_VIEW_VALUE_EDEFAULT.equals(dependsOnViewValue);
      case HdbSequencePackage.HDB_SEQUENCE_ELEMENTS__VALUE:
        return value != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (schema: ");
    result.append(schema);
    result.append(", schemaValue: ");
    result.append(schemaValue);
    result.append(", incrementBy: ");
    result.append(incrementBy);
    result.append(", incrementByValue: ");
    result.append(incrementByValue);
    result.append(", startWith: ");
    result.append(startWith);
    result.append(", startWithValue: ");
    result.append(startWithValue);
    result.append(", maxValue: ");
    result.append(maxValue);
    result.append(", maxValueValue: ");
    result.append(maxValueValue);
    result.append(", noMaxValue: ");
    result.append(noMaxValue);
    result.append(", noMaxValueValue: ");
    result.append(noMaxValueValue);
    result.append(", minValue: ");
    result.append(minValue);
    result.append(", minVlaueValue: ");
    result.append(minVlaueValue);
    result.append(", noMinValue: ");
    result.append(noMinValue);
    result.append(", noMinValueValue: ");
    result.append(noMinValueValue);
    result.append(", cycles: ");
    result.append(cycles);
    result.append(", cyclesValue: ");
    result.append(cyclesValue);
    result.append(", public: ");
    result.append(public_);
    result.append(", publicValue: ");
    result.append(publicValue);
    result.append(", dependsOnTable: ");
    result.append(dependsOnTable);
    result.append(", dependsOnTableValue: ");
    result.append(dependsOnTableValue);
    result.append(", dependsOnView: ");
    result.append(dependsOnView);
    result.append(", dependsOnViewValue: ");
    result.append(dependsOnViewValue);
    result.append(')');
    return result.toString();
  }

} //HdbSequenceElementsImpl
