/*
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbsequence.ide


/**
 * Use this class to register ide components.
 */
class HdbSequenceIdeModule extends AbstractHdbSequenceIdeModule {
}
