/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)/* 
@InjectWith(/* name is null */) */
@SuppressWarnings("all")
public class ModelParsingTest {
  @Inject
  private /* ParseHelper<HdbDD> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field ModelParsingTest.parseHelper refers to the missing type HdbDD"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
