/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelStandaloneSetup /* implements ModelStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type ModelStandaloneSetup");
  }
}
