/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd;

import com.sap.xsk.models.hdbdd.ModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelStandaloneSetup extends ModelStandaloneSetupGenerated {
  public static void doSetup() {
    new ModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
