/*
 * Copyright (c) 2019-2020 SAP SE or an SAP affiliate company and XSK contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, v2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-FileCopyrightText: 2019-2020 SAP SE or an SAP affiliate company and XSK contributors
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.sap.ndb.bimodelcube;

import com.sap.ndb.bimodeldatafoundation.QualifiedAttributeReference;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class describes the dimensionality of a measure. This means which (exception) aggregation is
 * used along a certain attribute (dimension)
 *
 *
 * <p>Java class for MeasureDimensionality complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MeasureDimensionality"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="attribute" type="{http://www.sap.com/ndb/BiModelDataFoundation.ecore}QualifiedAttributeReference" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="exceptionAggregationType" type="{http://www.sap.com/ndb/BiModelCube.ecore}ExceptionAggregationType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureDimensionality", propOrder = {
    "attribute"
})
public class MeasureDimensionality {

  @XmlElement(required = true)
  protected List<QualifiedAttributeReference> attribute;
  @XmlAttribute(name = "exceptionAggregationType")
  protected ExceptionAggregationType exceptionAggregationType;

  /**
   * Gets the value of the attribute property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the attribute property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getAttribute().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link QualifiedAttributeReference }
   */
  public List<QualifiedAttributeReference> getAttribute() {
    if (attribute == null) {
      attribute = new ArrayList<QualifiedAttributeReference>();
    }
    return this.attribute;
  }

  /**
   * Gets the value of the exceptionAggregationType property.
   *
   * @return possible object is
   * {@link ExceptionAggregationType }
   */
  public ExceptionAggregationType getExceptionAggregationType() {
    return exceptionAggregationType;
  }

  /**
   * Sets the value of the exceptionAggregationType property.
   *
   * @param value allowed object is
   *              {@link ExceptionAggregationType }
   */
  public void setExceptionAggregationType(ExceptionAggregationType value) {
    this.exceptionAggregationType = value;
  }

}
