/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.xsodata;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XSODataRuntimeModule extends AbstractXSODataRuntimeModule {

}
