/*
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.xsodata.parser.antlr;

import com.google.inject.Inject;
import com.sap.xsk.models.xsodata.parser.antlr.internal.InternalXSODataParser;
import com.sap.xsk.models.xsodata.services.XSODataGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XSODataParser extends AbstractAntlrParser {

  @Inject
  private XSODataGrammarAccess grammarAccess;

  @Override
  protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
    tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
  }


  @Override
  protected InternalXSODataParser createParser(XtextTokenStream stream) {
    return new InternalXSODataParser(stream, getGrammarAccess());
  }

  @Override
  protected String getDefaultRuleName() {
    return "XSOData";
  }

  public XSODataGrammarAccess getGrammarAccess() {
    return this.grammarAccess;
  }

  public void setGrammarAccess(XSODataGrammarAccess grammarAccess) {
    this.grammarAccess = grammarAccess;
  }
}
