/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbti.ide;

import com.google.inject.Injector;
import com.sap.xsk.models.hdbti.HdbtiStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HdbtiIdeSetup extends HdbtiStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from HdbtiRuntimeModule to Module"
      + "\nType mismatch: cannot convert from HdbtiIdeModule to Module");
  }
}
