/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.xsodata.scoping;

import com.sap.xsk.models.xsodata.scoping.AbstractModelScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ModelScopeProvider extends AbstractModelScopeProvider {
}
