/*
 * Copyright (c) 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, v2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-FileCopyrightText: 2019-2021 SAP SE or an SAP affiliate company and XSK contributors
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:54:28 AM EET 
//


package com.sap.ndb.bimodelcalculation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A view/node allows to rank rows and filter according to the rank
 *
 *
 * <p>Java class for RankView complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RankView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sap.com/ndb/BiModelCalculation.ecore}CalculationView"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="windowFunction" type="{http://www.sap.com/ndb/BiModelCalculation.ecore}WindowFunction"/&gt;
 *         &lt;element name="rankingFilter" type="{http://www.sap.com/ndb/BiModelCalculation.ecore}RankingFilter"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="allowFilterPushdown" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RankView", propOrder = {
    "windowFunction",
    "rankingFilter"
})
public class RankView
    extends CalculationView {

  protected WindowFunction windowFunction;
  protected RankingFilter rankingFilter;
  @XmlAttribute(name = "allowFilterPushdown")
  protected Boolean allowFilterPushdown;

  /**
   * Gets the value of the windowFunction property.
   *
   * @return possible object is
   * {@link WindowFunction }
   */
  public WindowFunction getWindowFunction() {
    return windowFunction;
  }

  /**
   * Sets the value of the windowFunction property.
   *
   * @param value allowed object is
   *              {@link WindowFunction }
   */
  public void setWindowFunction(WindowFunction value) {
    this.windowFunction = value;
  }

  /**
   * Gets the value of the rankingFilter property.
   *
   * @return possible object is
   * {@link RankingFilter }
   */
  public RankingFilter getRankingFilter() {
    return rankingFilter;
  }

  /**
   * Sets the value of the rankingFilter property.
   *
   * @param value allowed object is
   *              {@link RankingFilter }
   */
  public void setRankingFilter(RankingFilter value) {
    this.rankingFilter = value;
  }

  /**
   * Gets the value of the allowFilterPushdown property.
   *
   * @return possible object is
   * {@link Boolean }
   */
  public Boolean isAllowFilterPushdown() {
    return allowFilterPushdown;
  }

  /**
   * Sets the value of the allowFilterPushdown property.
   *
   * @param value allowed object is
   *              {@link Boolean }
   */
  public void setAllowFilterPushdown(Boolean value) {
    this.allowFilterPushdown = value;
  }

}
