/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.xsodata.xsOData;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sap.xsk.models.xsodata.xsOData.XsODataPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
