/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sap.xsk.models.hdbdd.model.Context#getTypes <em>Types</em>}</li>
 *   <li>{@link com.sap.xsk.models.hdbdd.model.Context#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see com.sap.xsk.models.hdbdd.model.ModelPackage#getContext()
 * @model
 * @generated
 */
public interface Context extends Type
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link com.sap.xsk.models.hdbdd.model.TypeDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see com.sap.xsk.models.hdbdd.model.ModelPackage#getContext_Types()
   * @model containment="true"
   * @generated
   */
  EList<TypeDefinition> getTypes();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.sap.xsk.models.hdbdd.model.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.sap.xsk.models.hdbdd.model.ModelPackage#getContext_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

} // Context
