/**
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbdd.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Namespace</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sap.xsk.models.hdbdd.model.ModelPackage#getNamespace()
 * @model
 * @generated
 */
public interface Namespace extends Type
{
} // Namespace
