/*
 * generated by Xtext 2.18.0
 */
package com.sap.xsk.models.hdbti.tests

import com.google.inject.Inject
import com.sap.xsk.models.hdbti.myHdbti.HdbdtiModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(HdbtiInjectorProvider)
class HdbtiParsingTest {
	@Inject
	ParseHelper<HdbdtiModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			import = [
					   {
					     table = "myTable";
					     schema = "mySchema";
					     file = "sap.ti2.demo:myData.csv";
					     header = false;
					     delimField = ";";
					     delimEnclosing="\"";
					   }
					 ];
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
	
	
	/**
	 * 				import = [
					   {
					     table = "myTable";
					     schema = "mySchema";
					     file = "sap.ti2.demo:myData.csv";
					     header = false;
					     useHeaderNames = false;
					     delimField = ";";
					     delimEnclosing="\"";
					     distinguishEmptyFromNull = true;
					     keys = [ "GROUP_TYPE" : "BW_CUBE", "GROUP_TYPE" : "BW_DSO", "GROUP_TYPE" : "BW_PSA"];
					   }
					 ];
	 */
}
